import type { NeighborhoodDefinition } from './types';

export const mapleStreet: NeighborhoodDefinition = {
  id: 'maple-street',
  name: 'Maple Street',
  tileSize: 64,
  legend: {
    R: { kind: 'road' },
    I: { kind: 'intersection' },
    S: { kind: 'sidewalk' },
    L: { kind: 'lawn' },
    D: { kind: 'driveway' },
    H: { kind: 'house', collides: true },
    X: { kind: 'hedge', collides: true },
  },
  rows: [
    'LLLLLHHHHLLXLLLLLHHHHLLLLLHHHHLLLLL',
    'LLLLLHHHHLLXLLLLLHHHHLLLLLHHHHLLLLL',
    'LLLLLDDDDSSSLLLLLDDDDSSSLLLLLDDDDLL',
    'LLLLLLLLLSSSLLLLLLLLLLSSSLLLLLLLLLL',
    'SSSSSSSSSSRSSSSSSSSSSSRSSSSSSSSSSSS',
    'RRRRRRRRRRIRRRRRRRRRRRIRRRRRRRRRRRR',
    'RRRRRRRRRRIRRRRRRRRRRRIRRRRRRRRRRRR',
    'SSSSSSSSSSRSSSSSSSSSSSRSSSSSSSSSSSS',
    'LLLLLLLLLSSSLLLLLLLLLLSSSLLLLLLLLLL',
    'LLLLLDDDDSSSLLLLLDDDDSSSLLLLLDDDDLL',
    'LLLLLHHHHLLXLLLLLHHHHLLLLLHHHHLLLLL',
    'LLLLLHHHHLLXLLLLLHHHHLLLLLHHHHLLLLL',
    'LLLLLLLLLSSSLLLLLLLLLLSSSLLLLLLLLLL',
    'SSSSSSSSSSRSSSSSSSSSSSRSSSSSSSSSSSS',
    'RRRRRRRRRRIRRRRRRRRRRRIRRRRRRRRRRRR',
    'RRRRRRRRRRIRRRRRRRRRRRIRRRRRRRRRRRR',
    'SSSSSSSSSSRSSSSSSSSSSSRSSSSSSSSSSSS',
    'LLLLLLLLLSSSLLLLLLLLLLSSSLLLLLLLLLL',
    'LLLLLDDDDSSSLLLLLDDDDSSSLLLLLDDDDLL',
    'LLLLLHHHHLLXLLLLLHHHHLLLLLHHHHLLLLL',
    'LLLLLHHHHLLXLLLLLHHHHLLLLLHHHHLLLLL',
  ],
  playerSpawn: { x: 8.5, y: 5.5 },
};

export const neighborhoods = {
  [mapleStreet.id]: mapleStreet,
};
